### ISSUE TITLE
[Enhancement] Folder Support

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/prorpgitems#81] opened 2021-12-29 17:11 UTC
**Describe the solution you'd like**

Add support for folders in all modules that allow you to put files in. It gets messy when you create lots of files without a way to sort or separate them.

**Comment by MaksyKun** [comment] 2023-07-20 16:53
Duplicate of [Issue #147](https://github.com/promcteam/prorpgitems/issues/147)
The feature is implemented.

**Closed by MaksyKun** 2023-07-20 16:53 UTC
Labels: enhancement
