### ISSUE TITLE
[Bug]Could not pass event EnginePlayerPacketEvent to ProMCCore v1.0.2-ALPHA

### ISSUE THREAD

**Issue by 1600496156** [promcteam/prorpgitems#18] opened 2021-08-04 09:13 UTC
**Describe the bug**
  Console warning

**To Reproduce**
Example steps (replace with your steps)

  start server and stop server no warning
  When a player enters the server .The console begins to display a warning message

**latest.log**

UUID of player 1600496156 is ce9e834b-fb23-3d6a-9ced-aeaea969468a
 java.lang.reflect.InvocationTargetException
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
 	at ProMCCore-1.0.2-ALPHA.jar//mc.promcteam.engine.utils.Reflex.invokeMethod(Reflex.java:160)
 	at ProRPGItems-1.0.2-ALPHA.jar//su.nightexpress.quantumrpg.nms.packets.versions.V1_17_R1.manageEquipmentChanges(V1_17_R1.java:101)
 	at ProRPGItems-1.0.2-ALPHA.jar//su.nightexpress.quantumrpg.nms.packets.versions.V1_17_R1.managePlayerPacket(V1_17_R1.java:61)
 	at ProMCCore-1.0.2-ALPHA.jar//mc.promcteam.engine.nms.packets.PacketManager.onPacketOut(PacketManager.java:128)
 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor116.execute(Unknown Source)
 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
 	at ProMCCore-1.0.2-ALPHA.jar//mc.promcteam.engine.nms.packets.PacketManager$1.write(PacketManager.java:100)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at java.base/java.lang.Thread.run(Thread.java:831)
 Caused by: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
 	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2052)
 	at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1483)
 	... 31 more

  Could not pass event EnginePlayerPacketEvent to ProMCCore v1.0.2-ALPHA
java.lang.NullPointerException: Cannot invoke "su.nightexpress.quantumrpg.QuantumRPG.getUserManager()" because "this.plugin" is null
	at su.nightexpress.quantumrpg.nms.packets.versions.V1_17_R1.manageEntityNames(V1_17_R1.java:234) ~[ProRPGItems-1.0.2-ALPHA.jar:?]
	at su.nightexpress.quantumrpg.nms.packets.versions.V1_17_R1.managePlayerPacket(V1_17_R1.java:65) ~[ProRPGItems-1.0.2-ALPHA.jar:?]
	at mc.promcteam.engine.nms.packets.PacketManager.onPacketOut(PacketManager.java:128) ~[ProMCCore-1.0.2-ALPHA.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor116.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-156]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-156]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-156]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-156]
	at mc.promcteam.engine.nms.packets.PacketManager$1.write(PacketManager.java:100) ~[ProMCCore-1.0.2-ALPHA.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[patched_1.17.1.jar:git-Paper-156]
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.a(Connection.java:315) ~[app:?]
	at net.minecraft.network.Connection.lambda$sendPacket$4(Connection.java:295) ~[app:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-156]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:831) [?:?]
**Versions (please complete the following information):**
 - Server Version: git-Paper-156 (MC: 1.17.1)
 - Plugin Version: ProRPGItems-1.0.2-ALPHA.jar;  ProMCCore-1.0.2-ALPHA.jar

[latest.log](https://github.com/promcteam/prorpgitems/files/6930057/latest.log)

**Comment by goflishMC** [comment] 2021-08-04 12:25
Duplicate of #16

**Closed by goflishMC** 2021-08-04 12:25 UTC
Labels: bug
