### ISSUE TITLE
Names being weird

### ISSUE THREAD

**Issue by Tainted-Valor** [promcteam/prorpgitems#165] opened 2022-12-18 16:24 UTC
So the problem I'm having is my textures certain ones only work if it's the exact name of the item but when I try to remove common it puts a space in front of the name but if I have the common my textures don't work and the space makes it so it doesn't work either I've attached images with examples though the textures work on that name specifically.

Discord discussion: https://discord.com/channels/818973833570680882/1053472408402665572

**Comment by Travja** [comment] 2022-12-29 08:07
I'm actually unable to reproduce this bug as described or as broken down in Discord.

**Comment by Travja** [comment] 2023-02-18 00:22
Just going to close this as it's not blocking Valor anymore and I am unable to reproduce the problem.

**Closed by Travja** 2023-02-18 00:22 UTC
Labels: bug
