### ISSUE TITLE
[Bug]: Sets do not display Active/inactive status for equiped items

### ISSUE THREAD

**Issue by FatalBlade** [promcteam/prorpgitems#121] opened 2022-05-23 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/22067704/169873182-97c51670-7b67-4304-9d06-f2a221f0acd1.png)
Shown is a screen shot of a player wearing the helm and legs but the item lore shows all items as inactive.

Set bonus is working as expected however.

### Expected Behavior

Currently equipped items in the lore to change color the inactive to active color per the config.

### Steps To Reproduce

Using default set one first needs to change the "name" line and add a space between %prefix% and leggings. I have also used the prefix Damp instead of broken but this does not make a difference.

I used the command /itemgen give playername common 4 36 
until I had enough items to get the set bonus

### Environment

```markdown
- Server Software: Spigot 1.18.2
- ProRPGItems Version: 1.0.3.8-1150257
- ProMCCore Version: 1.0.3.15-110257
- Plugins: dtlTraders-6.4.12, Citizens-2.0.29-b2548, EssentialsX-2.20.0-dev+5-d891268, HolographicDisplays, Vault
```

### latest.log

Wildcat.yml: https://pastebin.com/q4riQb45
Common.yml: https://pastebin.com/XpKe54Yn

**Comment by Travja** [comment] 2022-06-29 04:52
I'm going to close this as I don't believe this is really a bug. The reason this is happening is actually because you're in creative mode. The plugin is set up to not bother updating the item information if the player is in creative mode. If the player is in survival, however, I was not able to reproduce this. Only in creative did I see the same result.

**Closed by Travja** 2022-06-29 04:52 UTC
Labels: bug
