### ISSUE TITLE
[Bug]: Every Block or Item Interracted with in many ways are given undesired NBT tags - majorly breaking compatability!

### ISSUE THREAD

**Issue by P-paj** [promcteam/prorpgitems#90] opened 2022-01-04 23:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whether its given from creative mode, mined, crafted, taken from a chest, or anything - all items are given the NBT tags:

![image](https://user-images.githubusercontent.com/51720134/148138567-810b7190-644b-4487-ada1-3e92c92d15bf.png)

This breaks this plugins compatibility with many many other plugins - like trader npcs who check for items, or quests that are looking for specific items, or player shops looking for item data in buys/selling.

### Expected Behavior

ProRPGItems shouldn't need to add NBT tags to every item to specify that they do 1 damage - If an item doesn't have the flag, just assume it's one damage.

On my server, countless items now have these useless tags and many systems aren't working at all for players -- when this is fixed if there could be some way to automatically REMOVE those flags from the items they have effected, it would save me and probably other servers lots of work in fixing them up in another way, and would be very appreciated.

### Steps To Reproduce

Just - go into creative and give yourself blocks, or mine some, or interact with any item in nearly any way and the NBT flags will appear.

### Environment

```markdown
- Server Software: Paper
- ProRPGItems Version: Proskillapi 1.1.7.13
- ProMCCore Version: 1.0.3.5
```

**Comment by Travja** [comment] 2022-01-10 06:07
Basically a duplicate of #77. Should be resolved in further builds.

**Closed by Travja** 2022-01-10 06:07 UTC
Labels: bug

**Comment by Travja** [comment] 2022-01-10 06:10
Eh. Or I just fixed it so it removes that flag too :P
